version: '3'

services:
  notes-db:
    image: postgres:11.5
    container_name: notes-db
    hostname: notes-db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - notes-network
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  notes-adminer:
    image: adminer
    container_name: notes-adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - notes-network

networks:
  notes-network:
    driver: bridge