version: '3'

services:
  web:
    container_name: notes-web
    restart: always
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/app.dev.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - notes-network
  
  api:
    container_name: notes-api
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - notes-network

  db:
    image: postgres:11.5
    container_name: notes-db
    hostname: notes-db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - notes-network
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: notes-adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - notes-network

networks:
  notes-network:
    driver: bridge