---
- hosts: ec2_instances
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name:
          - docker.io
          - python3-pip
        state: present

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present
        executable: pip3
    
    - name: Copy docker-compose.yml
      copy:
        src: ../../docker-compose.prod.yml
        dest: notes/
    
    - name: Copy nginx configuration
      copy:
        src: ../../nginx/
        dest: notes/nginx/

    - name: Copy .env file
      copy:
        src: ../../.env.prod
        dest: notes/.env
    
    - name: Copy certs folder
      copy:
        src: ../../certs/
        dest: notes/certs/

    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: 
          - "docker==6.1.3"
          - "docker-compose"

    - name: Log into DockerHub
      community.docker.docker_login:
        username: '{{  docker_hub_username  }}'
        password: '{{ docker_hub_password }}'
    
    - name: Run `docker-compose file`
      community.docker.docker_compose:
        project_src: "notes/"
        files:
          - docker-compose.prod.yml
        state: present