name: Notes CI

on:
  push:
    branches:
      - staging

  pull_request:
    branches:
      - staging

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install && pnpm install express
          
      - name: Lint Project web
        run: pnpm nx lint web

      - name: Lint Project api
        run: pnpm nx lint api


      - name: Generate .env file
        run: |
          echo "ERROR_LOG=./logs/api/error.log" > .env
          echo "DB_HOST=127.0.0.1" > .env
          echo "DB_PORT=5432" >> .env
          echo "DB_USER=test" >> .env
          echo "DB_PASSWORD=test" >> .env
          echo "DB_NAME=test" >> .env
          echo "DB_SYNC=true" >> .env
          echo "DB_LOGGING=true" >> .env
          echo "POSTGRES_USER=test" >> .env
          echo "POSTGRES_PASSWORD=test" >> .env
          echo "POSTGRES_DB=test" >> .env

      - name: Start db container
        run: docker-compose up -d db
  
      - name: Start Project api
        run: pnpm nx serve api &

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps

      - name: Test Project web
        run: pnpm nx e2e web-e2e

      - name: Buid Project api
        run: pnpm nx build api
      
      - name: Buid Project web
        run: pnpm nx build web

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract version number
        run: |
          # Extract the version number
          commit_message=$(git log -1 --pretty=%B)

          version=$(echo "$commit_message" | grep -oP 'staging/v\K[0-9]+\.[0-9]+\.[0-9]+')

          echo "build version number: $version"
          echo "VERSION=$version" >> $GITHUB_ENV
      
      - name: Build and push web
        uses: docker/build-push-action@v5
        with:
          context: "."
          file: ./docker/web.Dockerfile
          push: true
          tags: aimadjaouhar/notes:web-${{ env.VERSION }}

      - name: Build and push api
        uses: docker/build-push-action@v5
        with:
          context: "."
          file: ./docker/api.Dockerfile
          push: true
          tags: aimadjaouhar/notes:api-${{ env.VERSION }}


