name: Notes CI

on:
  push:
    branches:
      - staging

  pull_request:
    branches:
      - staging

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        
      - name: Lint Project web
        run: pnpm nx lint web

      - name: Lint Project api
        run: pnpm nx lint api

      - name: Start db container
        run: docker-compose up -d db
  
      - name: Start database
        run: pnpm nx serve api

      - name: Test Project web
        run: pnpm nx e2e web-e2e

      - name: Buid Project api
        run: pnpm nx build api --skip-cache
      
      - name: Buid Project web
        run: pnpm nx build web --skip-cache

      # - uses: docker/setup-buildx-action@v3
      # - uses: docker/setup-qemu-action@v3

      # - name: Login to Docker Hub
      # - uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      # - name: Build and push web
      # - uses: docker/build-push-action@v5
      #   with:
      #     context: "."
      #     file: ./docker/web.Dockerfile
      #     push: true
      #     tags: aimadjaouhar/notes:web-${{ env.VERSION }}

      # - name: Build and push api
      # - uses: docker/build-push-action@v5
      #   with:
      #     context: "."
      #     file: ./docker/api.Dockerfile
      #     push: true
      #     tags: aimadjaouhar/notes:api-${{ env.VERSION }}






